CREATE TABLE item_ventas
(numero_factura INT NOT NULL,
codigo_producto INT NOT NULL,
cantidad INT,
precio INT,
PRIMARY KEY (codigo_producto),
FOREIGN KEY (codigo_producto) REFERENCES productos
(pnro));


CREATE TABLE PRODUCTOS
(PNRO INT NOT NULL,
PNOMBRE VARCHAR(20) NOT NULL,
PRECIO INT NOT NULL,
TAMAÑO VARCHAR(20),
LOCALIDAD VARCHAR(12) NOT NULL,
PRIMARY KEY (PNRO));

CREATE TABLE proveedores_productos
(NUMERO INT NOT NULL,
PNRO INT NOT NULL,
CANTIDAD INT NOT NULL,
PRIMARY KEY (NUMERO, PNRO),
FOREIGN KEY (NUMERO) REFERENCES PROVEEDORES
(NUMERO),
FOREIGN KEY (PNRO) REFERENCES PRODUCTOS (PNRO));